[package]
name = "bacnet-integration-tests"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
ipv6 = ["bacnet-transport/ipv6"]
ethernet = ["bacnet-transport/ethernet"]

[dev-dependencies]
bacnet-types.workspace = true
bacnet-encoding.workspace = true
bacnet-services.workspace = true
bacnet-transport.workspace = true
bacnet-network.workspace = true
bacnet-objects.workspace = true
bacnet-client.workspace = true
bacnet-server.workspace = true
bytes.workspace = true
serde_json = "1"
socket2 = { workspace = true, features = ["all"] }
libc.workspace = true
tokio = { workspace = true, features = ["net", "rt-multi-thread", "sync", "macros", "time", "test-util", "io-util"] }

[lints]
workspace = true
